import axios from "axios";
import { useEffect, useState } from "react";

const ThirtyDays = ({ token }) => {
  const [comment, setComment] = useState("");

  const currentDate = new Date();
  const currentMonth = currentDate.getMonth();
  const daysInMonth = new Date(
    currentDate.getFullYear(),
    currentMonth + 1,
    0
  ).getDate();

  const formattedDate =
    currentDate.toISOString().split("T")[0] +
    "T" +
    ("0" + currentDate.getHours()).slice(-2) +
    ":" +
    ("0" + currentDate.getMinutes()).slice(-2) +
    ":" +
    ("0" + currentDate.getSeconds()).slice(-2);

  const [soldItems, setSoldItems] = useState(Array(daysInMonth).fill(""));
  const [dayComment, setDayComment] = useState(Array(daysInMonth).fill(""));
  const [invoices, setInvoices] = useState(Array(daysInMonth).fill(""));
  const [transactionAmount, setTransactionAmount] = useState(
    Array(daysInMonth).fill("")
  );

  const handleDayComment = (index, value) => {
    const newDayComment = [...dayComment];
    newDayComment[index] = value;
    setDayComment(newDayComment);
  };

  const handleInvoicesChange = (index, value) => {
    const newInvoices = [...invoices];
    newInvoices[index] = value;
    setInvoices(newInvoices);
  };

  const handleTransactionAmountChange = (index, value) => {
    const newTransactionAmount = [...transactionAmount];
    newTransactionAmount[index] = value;
    setTransactionAmount(newTransactionAmount);
  };

  const handleSoldItemsChange = (index, value) => {
    const newSoldItems = [...soldItems];
    newSoldItems[index] = value;
    setSoldItems(newSoldItems);
  };

  const bearerToken = token;
  const headers = {
    tenant: "mgb.map.eaglehills.com",
    "Ocp-Apim-Subscription-Key": "b652a304ec8143f8aeb8a879c9911f45",
    Authorization: `Bearer ${bearerToken}`,
    "Content-Type": "application/json",
  };
  const body = {
    LeaseCode: "t0001235",
    SalesTypeCode: "fnb",
    PropertyCode: "mgb",
    TransactionDate: formattedDate, //"2022-01-01T00:00:00"
    TransactionSource: 1,
    RequestStatus: 2,
    SalesRequestComments: comment,
    TransactionType: 1,
    SalesRequestId: 0,

    BulkSalesModels: [
      {
        LeaseCode: "t0001235",
        SalesTypeCode: "fnb",
        PropertyCode: "mgb",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TransactionType: 1,
        TransactionDate: "2022-01-01T00:00:00",
        TotalInvoices: 1,
        TotalItemSold: 3,
        TransactionAmount: 0,
        SaleTransactionComments: "",
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        TransactionId: 0,
        TransactionNumber: null,
        Year: 0,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
      },
      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-02T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-03T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-04T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-05T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-06T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-07T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-08T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-09T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-10T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-11T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-12T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-13T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-14T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-15T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-16T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-17T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-18T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-19T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-20T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-21T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-22T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-23T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-24T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-25T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-26T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-27T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-28T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-29T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-30T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },

      {
        TransactionId: 0,
        TransactionNumber: null,
        TransactionDate: "2022-01-31T00:00:00",
        TransactionAmount: 0,
        LeaseCode: "t0001235",
        PropertyCode: "mgb",
        Year: 0,
        TransactionType: 1,
        CreatedUserId: 0,
        CreatedByEmail: null,
        CustomerCode: null,
        FileAttachmentBase64: null,
        FileAttachmentTitle: null,
        FileAttachmentContentType: null,
        SaleTransactionComments: "",
        SaleTransactionStatus: 2,
        SaleTransactionSource: 1,
        TotalInvoices: 1,
        TotalItemSold: 3,
        PropertyName: null,
        ModifiedBy: 0,
        ModifiedByName: null,
        TransactionAmount_Str: null,
        TotalInvoices_Str: null,
        TotalItemSold_Str: null,
        SubmissionDate: "0001-01-01T00:00:00",
        SubmissionDate_Str: null,
        SalesTypeCode: "fnb",
      },
    ],

    PropertyName: null,
    LeaseUnitCode: null,
    LeaseBrandName: null,

    TransactionYear: null,

    TransactionDate_Str: null,
    SaleTransactionStatus_Str: null,
    Day: 0,
    Month: 0,
    Year: 0,
    RequestNumber: null,
    ContactCode: null,
    CreatedUserId: 0,
    CreatedByEmail: null,
    SalesType: null,
    TransactionTypeStr: null,
    SaleTransactionSourceStr: null,

    GrandTotalTransactionAmount: 0,
    GrandTotalTransactionAmount_Str: null,
    GrandTotalTotalInvoices: 0,
    GrandTotalTotalInvoices_Str: null,
    GrandTotalTotalItemSold: 0,
    GrandTotalTotalItemSold_Str: null,
  };

  const handleSubmit = () => {
    const updatedBulkSalesModels = body.BulkSalesModels.map((item, index) => ({
      ...item,
      TotalInvoices: parseInt(invoices[index]),
      TotalItemSold: parseInt(soldItems[index]),
      TransactionAmount: parseFloat(transactionAmount[index]),
    }));

    axios
      .post(
        "https://azmapapimgmtprod1.azure-api.net/bulkSalesinfo/api/BulkSales",
        {
          ...body,
          BulkSalesModels: updatedBulkSalesModels,
        },
        { headers: headers }
      )
      .then((response) => {
        console.log(body, response.data);
      })
      .catch((error) => {
        console.error(error);
      });
  };
  useEffect(() => {
    console.log(body);
  }, [soldItems, invoices, transactionAmount, comment]);

  return (
    <>
      {[...Array(daysInMonth).keys()].map((day, index) => (
        <div key={index} className="w-4/5 flex flex-col items-start text-left">
          <h3 className="self-left text-[#fff] text-xl mb-3 tracking-widest">
            {day + 1} - {currentMonth + 1} - 2024
          </h3>
          <div className="flex w-full items-start space-x-10 pb-5">
            <input
              type="number"
              className="w-2/6 py-5 border-b-[1px] border-[#fff] px-3 bg-[rgba(255,255,255,0.85)] placeholder:text-[#000] text-[#000]"
              placeholder="Number of Sold Items"
              value={soldItems[index]}
              onChange={(e) => handleSoldItemsChange(index, e.target.value)}
              required
            />
            <input
              type="number"
              className="w-2/6 py-5 border-b-[1px] border-[#fff] px-3 bg-[rgba(255,255,255,0.85)] placeholder:text-[#000] text-[#000]"
              placeholder="Number of Invoices"
              value={invoices[index]}
              onChange={(e) => handleInvoicesChange(index, e.target.value)}
              required
            />
            <input
              type="number"
              className="w-2/6 py-5 border-b-[1px] border-[#fff] px-3 bg-[rgba(255,255,255,0.85)] placeholder:text-[#000] text-[#000]"
              placeholder="Transaction Amount"
              value={transactionAmount[index]}
              onChange={(e) =>
                handleTransactionAmountChange(index, e.target.value)
              }
              required
            />
          </div>
          <input
            type="text"
            className="w-full py-5 border-b-[1px] border-[#fff] px-3 bg-[rgba(255,255,255,0.85)] placeholder:text-[#000] text-[#000]"
            placeholder="Any Comments ... (optional)"
            value={transactionAmount[index]}
            onChange={(e) => handleDayComment(index, e.target.value)}
          />
        </div>
      ))}
    </>
  );
};

export default ThirtyDays;
